# Generated by Django 3.2 on 2021-04-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0002_remove_staffmodel_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('appdatetime', models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date Time')),
                ('iscancelled', models.BooleanField(default='No', verbose_name='Cancelled')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
    ]
