# Generated by Django 3.2 on 2021-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='enddatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appdatetime',
            field=models.DateTimeField(blank=True, verbose_name='Start Date Time'),
        ),
    ]
