# Generated by Django 3.2 on 2021-05-24 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appdatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Appointment Date Time'),
            preserve_default=False,
        ),
    ]
