# Generated by Django 3.0.3 on 2021-03-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_servicerendered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('dateofbirth', models.DateField()),
                ('emailaddress', models.CharField(max_length=64)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(db_column='AppointmentID', primary_key=True, serialize=False)),
                ('appointmentdate', models.DateField()),
                ('appointmenttime', models.TimeField()),
                ('iscancelled', models.BooleanField(default='No')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Customer')),
            ],
        ),
    ]
