# Generated by Django 3.1.7 on 2021-03-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=24)),
                ('lastname', models.CharField(db_column='LastName', max_length=12)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=50)),
                ('contactnumber', models.IntegerField(db_column='ContactNumber')),
                ('username', models.CharField(db_column='Username', max_length=15)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
        ),
    ]
