# Generated by Django 3.0.3 on 2021-03-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('scheduling', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerendered',
            name='serviceid',
            field=models.ForeignKey(db_column='ServiceID', on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
