# Generated by Django 3.0.3 on 2021-03-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20210305_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
