# Generated by Django 3.1.7 on 2021-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='emailaddress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastname',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(db_column='Username', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(db_column='Username', max_length=15, null=True),
        ),
    ]
