version: '3.8'

services:
    db:
      image: mysql:5.7
      environment:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: beautywand_db
      healthcheck:
        test: ["CMD-SHELL", '/usr/bin/mysql --user=root --password=password --execute "SHOW DATABASE;']
        interval: 15s
        timeout: 2s
        retries: 3

    backend:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8000:8000
      working_dir: /app
      volumes:
        - .:/app
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DB: beautywand_db
      depends_on:
        - db

