# Generated by Django 3.2 on 2021-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='average_rating',
        ),
    ]
