# Generated by Django 3.2 on 2021-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffmodel_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
