# Generated by Django 3.2 on 2021-04-21 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=64, unique=True, verbose_name='Service Name')),
                ('servicetype', models.CharField(choices=[('Hair', 'Hair Service'), ('Nails', 'Nail Service'), ('Skin', 'Skin Service'), ('Makeup', 'Semi-permanent Makeup'), ('Face', 'Facial Service'), ('Eyes', 'Eyebrow/Eyelash Service')], max_length=32, verbose_name='Service Type')),
                ('serviceprice', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('servicedescription', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('serviceduration', models.DurationField(default=datetime.timedelta(seconds=1200), verbose_name='Duration')),
            ],
        ),
    ]
