# Generated by Django 3.0.3 on 2021-03-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ServiceDescription',
            new_name='servicedescription',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='ServiceDuration',
            new_name='serviceduration',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='ServiceName',
            new_name='servicename',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='ServicePrice',
            new_name='serviceprice',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='ServiceType',
            new_name='servicetype',
        ),
    ]
