# Generated by Django 3.2 on 2021-05-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('staff', '0002_rename_services_staffmodel_service'),
        ('services', '0003_alter_service_is_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdatetime', models.DateTimeField(blank=True, verbose_name='Start Date Time')),
                ('enddatetime', models.DateTimeField(blank=True, verbose_name='End Date Time')),
                ('iscancelled', models.BooleanField(default=False, verbose_name='Is it Cancelled')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is it Completed')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
    ]
