# Generated by Django 3.2 on 2021-05-22 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='clientname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='servicename',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='staffname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.event')),
            ],
        ),
    ]
