# Generated by Django 3.2 on 2021-05-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmodel',
            old_name='services',
            new_name='service',
        ),
    ]
