# Generated by Django 3.2.8 on 2021-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_services_staffmodel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
